# Generated by Django 5.0 on 2025-09-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("P", "Order Processing"),
                    ("S", "Shipping"),
                    ("D", "Delivered"),
                ],
                default="P",
                max_length=1,
            ),
        ),
    ]
