# Generated by Django 5.0 on 2025-09-17 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_order_order_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="order_status",
            new_name="status",
        ),
    ]
