# Generated by Django 5.0 on 2025-09-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
