# Generated by Django 5.0 on 2025-09-18 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_movies", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
